<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        \App\Models\User::create([
            'name' => 'admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('password'),
            'role_id' => 1,
        ]);

         \App\Models\User::create([
             'name' => 'Danielle',
             'email' => 'ipr@culturalcenter.gov.ph',
             'password' => bcrypt('imsupergay'),
             'role_id' => 1,
         ]);

         \App\Models\User::create([
             'name' => 'Jamie',
             'email' => 'jamie@gmail.com',
             'password' => bcrypt('jamiegwapo'),
             'role_id' => 1,
         ]);
         
        $tags = [
            ['name' => 'Apartment', 'slug' => 'apartment'],
            ['name' => 'Bahay Kubo', 'slug' => 'bahay-kubo'],
            ['name' => 'Bahay na Bato', 'slug' => 'bahay-na-bato'],
            ['name' => 'Barong-Barong', 'slug' => 'barong-barong'],
            ['name' => 'Bungalow', 'slug' => 'bungalow'],
            ['name' => 'Casa Real', 'slug' => 'casa-real'],
            ['name' => 'Commercial Buildings', 'slug' => 'commercial-buildings'],
            ['name' => 'Eskuwelahan', 'slug' => 'eskuwelahan'],
            ['name' => 'Gabaldon Schoolhouses', 'slug' => 'gabaldon-schoolhouses'],
            ['name' => 'Heritage Areas', 'slug' => 'heritage-areas'],
            ['name' => 'Houseboat', 'slug' => 'houseboat'],
            ['name' => 'Indigenous House', 'slug' => 'indigenous-house'],
            ['name' => 'Kamalig', 'slug' => 'kamalig'],
            ['name' => 'Kapitolyo', 'slug' => 'kapitolyo'],
            ['name' => 'Kuta', 'slug' => 'kuta'],
            ['name' => 'Kuweba', 'slug' => 'kuweba'],
            ['name' => 'Masjid', 'slug' => 'masjid'],
            ['name' => 'Munisipyo', 'slug' => 'munisipyo'],
            ['name' => 'Ospital', 'slug' => 'ospital'],
            ['name' => 'Palacio', 'slug' => 'palacio'],
            ['name' => 'Palengke', 'slug' => 'palengke'],
            ['name' => 'Parola', 'slug' => 'parola'],
            ['name' => 'Retablo', 'slug' => 'retablo'],
            ['name' => 'Rice Terraces', 'slug' => 'rice-terraces'],
            ['name' => 'Sabungan', 'slug' => 'sabungan'],
            ['name' => 'Sementeryo', 'slug' => 'sementeryo'],
            ['name' => 'Simbahan', 'slug' => 'simbahan'],
            ['name' => 'Sinehan', 'slug' => 'sinehan'],
            ['name' => 'Split-Level House', 'slug' => 'split-level-house'],
            ['name' => 'Teatro', 'slug' => 'teatro'],
            ['name' => 'Tree House', 'slug' => 'tree-house'],
            ['name' => 'Tribunal', 'slug' => 'tribunal'],
            ['name' => 'Tsalet', 'slug' => 'tsalet'],
            ['name' => 'Tulay', 'slug' => 'tulay'],
            ['name' => 'Advertisement', 'slug' => 'advertisement'],
            ['name' => 'Agriculture Programs', 'slug' => 'agriculture-programs'],
            ['name' => 'Aksiyon on Radio and Television', 'slug' => 'aksiyon-on-radio-and-television'],
            ['name' => 'Animation Programs', 'slug' => 'animation-programs'],
            ['name' => 'Arts and Culture Programs', 'slug' => 'arts-and-culture-programs'],
            ['name' => 'Balagtasan Programs', 'slug' => 'balagtasan-programs'],
            ['name' => "Children's Programs", 'slug' => 'childrens-programs'],
            ['name' => 'Counseling Programs', 'slug' => 'counseling-programs'],
            ['name' => 'Dokyu, Investigative Report, and Talk Public Affairs', 'slug' => 'dokyu-investigative-report-and-talk-public-affairs'],
            ['name' => 'Drama and Telenovela', 'slug' => 'drama-and-telenovela'],
            ['name' => 'Educational/Instructional Programs', 'slug' => 'educationa-instructional-programs'],
            ['name' => 'Faith-Based Programs', 'slug' => 'faith-based-programs'],
            ['name' => 'Game Shows', 'slug' => 'game-shows'],
            ['name' => 'Health Programs', 'slug' => 'health-programs'],
            ['name' => 'Horror and Fantasy Programs', 'slug' => 'horror-and-fantasy-programs'],
            ['name' => 'Komedi and Sitcom', 'slug' => 'komedi-and-sitcom'],
            ['name' => 'Legal Advice Shows and Legal Dramas', 'slug' => 'legal-advice-shows-and-legal-dramas'],
            ['name' => 'Magazine Programs', 'slug' => 'magazine-programs'],
            ['name' => 'Music Videos', 'slug' => 'music-videos'],
            ['name' => 'Music Programs and Musicals', 'slug' => 'music-programs-and-musicals'],
            ['name' => 'News Programs', 'slug' => 'news-programs'],
            ['name' => 'Reality Television', 'slug' => 'reality-television'],
            ['name' => 'Sports Broadcasting', 'slug' => 'sports-broadcasting'],
            ['name' => 'Talk Shows', 'slug' => 'talk-shows'],
            ['name' => 'Teleradyo', 'slug' => 'teleradyo'],
            ['name' => 'Television Specials', 'slug' => 'television-specials'],
            ['name' => 'Variety Shows', 'slug' => 'variety-shows'],
            ['name' => 'Aerobic Dance', 'slug' => 'aerobic-dance'],
            ['name' => 'Atang-atang', 'slug' => 'atang-atang'],
            ['name' => 'Balitaw Dance', 'slug' => 'balitaw-dance'],
            ['name' => 'Ballangbang', 'slug' => 'ballangbang'],
            ['name' => 'Ballet', 'slug' => 'ballet'],
            ['name' => 'Balse Dance', 'slug' => 'balse-dance'],
            ['name' => 'Banga', 'slug' => 'banga'],
            ['name' => 'Bangibang', 'slug' => 'bangibang'],
            ['name' => 'Bati', 'slug' => 'bati'],
            ['name' => 'Bendiyan', 'slug' => 'bendiyan'],
            ['name' => 'Binabayani', 'slug' => 'binabayani'],
            ['name' => 'Binanog', 'slug' => 'binanog'],
            ['name' => 'Bird Dances', 'slug' => 'bird-dances'],
            ['name' => 'Bodabil Dance', 'slug' => 'bodabil-dance'],
            ['name' => 'Buklog', 'slug' => 'buklog'],
            ['name' => 'Cheerdance', 'slug' => 'cheerdance'],
            ['name' => 'Courtship and Wedding Dances', 'slug' => 'courtship-and-wedding-dances'],
            ['name' => 'Cultural Dance', 'slug' => 'cultural-dance'],
            ['name' => 'Dancesport', 'slug' => 'dancesport'],
            ['name' => 'Dinuy-a', 'slug' => 'dinuy-a'],
            ['name' => 'Diyandi', 'slug' => 'diyandi'],
            ['name' => 'Dugso', 'slug' => 'dugso'],
            ['name' => 'Escotis/Chotis/Schottische', 'slug' => 'escotis-chotis-schottische'],
            ['name' => 'Folk Dance', 'slug' => 'folk-dance'],
            ['name' => 'Game Dance', 'slug' => 'game-dance'],
            ['name' => 'Habanera Dance', 'slug' => 'habanera-dance'],
            ['name' => 'Hip-hop Dance', 'slug' => 'hip-hop-dance'],
            ['name' => 'Itik-Itik', 'slug' => 'itik-itik'],
            ['name' => 'Jazz Dance', 'slug' => 'jazz-dance'],
            ['name' => 'Jota Dance', 'slug' => 'jota-dance'],
            ['name' => 'Kayaw', 'slug' => 'kayaw'],
            ['name' => 'Kumintang Dance', 'slug' => 'kumintang-dance'],
            ['name' => 'Kuradang', 'slug' => 'kuradang'],
            ['name' => 'Kuratsa', 'slug' => 'kuratsa'],
            ['name' => 'Lanceros', 'slug' => 'lanceros'],
            ['name' => 'Langka', 'slug' => 'langka'],
            ['name' => 'Lunsay', 'slug' => 'lunsay'],
            ['name' => 'Martial Dance', 'slug' => 'martial-dance'],
            ['name' => 'Mascota', 'slug' => 'mascota'],
            ['name' => 'Mazurka', 'slug' => 'mazurka'],
            ['name' => 'Mimetic Dance', 'slug' => 'mimetic-dance'],
            ['name' => 'Modern Dance', 'slug' => 'modern-dance'],
            ['name' => 'Pag-apir/Pig-apir', 'slug' => 'pag-apir-pig-apir'],
            ['name' => 'Pallo-ok', 'slug' => 'pallo-ok'],
            ['name' => 'Pandanggo Dance', 'slug' => 'pandanggo-dance'],
            ['name' => 'Pangalay/Igal/Pamansak', 'slug' => 'pangalay-igal-pamansak'],
            ['name' => 'Pantomina', 'slug' => 'pantomina'],
            ['name' => 'Paseo', 'slug' => 'paseo'],
            ['name' => 'Paso Doble', 'slug' => 'paso-doble'],
            // ['name' => 'Pastores', 'slug' => 'pastores'],
            ['name' => 'Pateado/Zapateado', 'slug' => 'pateado-zapateado'],
            ['name' => 'Pattong', 'slug' => 'pattong'],
            ['name' => 'Pattung', 'slug' => 'pattung'],
            ['name' => 'Pinanyoan', 'slug' => 'pinanyoan'],
            ['name' => 'Polka Dance', 'slug' => 'polka-dance'],
            ['name' => 'Polynesian and Tahitian Dances', 'slug' => 'polynesian-and-tahitian-dances'],
            ['name' => 'Rice Dances', 'slug' => 'rice-dances'],
            ['name' => 'Rigodon De Honor', 'slug' => 'rigodon-de-honor'],
            ['name' => 'Ritual Dancing', 'slug' => 'ritual-dancing'],
            ['name' => 'Sagayan', 'slug' => 'sagayan'],
            ['name' => 'Salidsid', 'slug' => 'salidsid'],
            ['name' => 'Sayaw sa Bangko', 'slug' => 'sayaw-sa-bangko'],
            ['name' => 'Singkil', 'slug' => 'singkil'],
            ['name' => 'Social Dancing', 'slug' => 'social-dancing'],
            ['name' => 'Song Dance', 'slug' => 'song-dance'],
            ['name' => 'Spanish Dance', 'slug' => 'spanish-dance'],
            ['name' => 'Street Dance', 'slug' => 'street-dance'],
            ['name' => 'Subli', 'slug' => 'subli'],
            ['name' => 'Surtido', 'slug' => 'surtido'],
            ['name' => 'Tadek Inlaud', 'slug' => 'tadek-inlaud'],
            ['name' => 'Takik', 'slug' => 'takik'],
            ['name' => 'Tap Dance', 'slug' => 'tap-dance'],
            ['name' => 'Tayao', 'slug' => 'tayao'],
            ['name' => 'Tinikling', 'slug' => 'tinikling'],
            ['name' => 'Tongatong', 'slug' => 'tongatong'],
            ['name' => 'Tumahik', 'slug' => 'tumahik'],
            ['name' => 'TV Dance', 'slug' => 'tv-dance'],
            ['name' => 'Aksiyon', 'slug' => 'aksiyon'],
            ['name' => 'Animation', 'slug' => 'animation'],
            ['name' => 'Bomba', 'slug' => 'bomba'],
            ['name' => 'Dokyu', 'slug' => 'dokyu'],
            ['name' => 'Film Drama', 'slug' => 'film-drama'],
            ['name' => 'Art Experimental', 'slug' => 'art-experimental'],
            ['name' => 'Fantasy and Science Fiction', 'slug' => 'fantasy-and-science-fiction'],
            ['name' => 'Historical', 'slug' => 'historical'],
            ['name' => 'Horror', 'slug' => 'horror'],
            ['name' => 'Komedi', 'slug' => 'komedi'],
            ['name' => 'Musical', 'slug' => 'musical'],
            ['name' => 'Period', 'slug' => 'period'],
            ['name' => 'Short Films', 'slug' => 'short-films'],
            ['name' => 'Epic', 'slug' => 'epic'],
            ['name' => 'Essay', 'slug' => 'essay'],
            ['name' => 'Folk Narrative', 'slug' => 'folk-narrative'],
            ['name' => 'Folk Poetry', 'slug' => 'folk-poetry'],
            ['name' => 'Folk Song', 'slug' => 'folk-song'],
            ['name' => 'Komiks', 'slug' => 'komiks'],
            ['name' => 'Metrical Romance', 'slug' => 'metric-romance'],
            ['name' => 'New Media', 'slug' => 'new-media'],
            ['name' => 'Novel', 'slug' => 'novel'],
            ['name' => 'Pasyon', 'slug' => 'pasyon'],
            ['name' => 'Poetry', 'slug' => 'poetry'],
            ['name' => 'Short Story', 'slug' => 'short-story'],
            ['name' => 'Art Song', 'slug' => 'art-song'],
            ['name' => 'Ballad', 'slug' => 'ballad'],
            ['name' => 'Balse Music', 'slug' => 'balse-music'],
            ['name' => 'Bamboo Music', 'slug' => 'bamboo-music'],
            ['name' => 'Chamber Music', 'slug' => 'chamber-music'],
            ['name' => 'Chant', 'slug' => 'chant'],
            ['name' => 'Choral Arrangement', 'slug' => 'choral-arrangement'],
            ['name' => 'Concerto', 'slug' => 'concerto'],
            ['name' => 'Film Music', 'slug' => 'film-music'],
            ['name' => 'Music', 'slug' => 'music'],
            ['name' => 'Habanera Music', 'slug' => 'habanera-music'],
            ['name' => 'Hip-Hop Music', 'slug' => 'hip-hop-music'],
            ['name' => 'Jazz Music', 'slug' => 'jazz-music'],
            ['name' => 'Jota Music', 'slug' => 'jota-music'],
            ['name' => 'Kumintang Music', 'slug' => 'kumintang-music'],
            ['name' => 'Kundiman', 'slug' => 'kundiman'],
            ['name' => 'Liturgical Music', 'slug' => 'liturgical-music'],
            ['name' => 'Marcha', 'slug' => 'marcha'],
            ['name' => 'Novelty Song', 'slug' => 'novelty'],
            ['name' => 'Opera', 'slug' => 'opera'],
            ['name' => 'Pandanggo Music', 'slug' => 'pandanggo-music'],
            ['name' => 'Polka Music', 'slug' => 'polka-music'],
            ['name' => 'Pop Music', 'slug' => 'pop-music'],
            ['name' => 'Protest Songs', 'slug' => 'protest-songs'],
            ['name' => 'Rigodon', 'slug' => 'rigodon'],
            ['name' => 'Rock Music', 'slug' => 'rock-music'],
            ['name' => 'Solo Instrumental Literature', 'slug' => 'solo-instrumental-literature'],
            ['name' => 'Sonata', 'slug' => 'sonata'],
            ['name' => 'Song Debate', 'slug' => 'song-debate'],
            ['name' => 'Sound Art', 'slug' => 'sound-art'],
            ['name' => 'Symphonic Literature', 'slug' => 'symphoninc-literatures'],
            ['name' => 'Villancico', 'slug' => 'villancico'],
            ['name' => 'Band', 'slug' => 'band'],
            ['name' => 'Choral Groups', 'slug' => 'choral-groups'],
            ['name' => 'Orchestra', 'slug' => 'orchestra'],
            ['name' => 'Rondalla', 'slug' => 'rondalla'],
            ['name' => 'Bandurria', 'slug' => 'bandurria'],
            ['name' => 'Buzzer', 'slug' => 'buzzer'],
            ['name' => 'Clapper', 'slug' => 'clapper'],
            ['name' => 'Drums', 'slug' => 'drums'],
            ['name' => 'Fiddle', 'slug' => 'fiddle'],
            ['name' => 'Flute', 'slug' => 'flute'],
            ['name' => 'Gongs', 'slug' => 'gongs'],
            ['name' => 'Guitar', 'slug' => 'guitar'],
            ['name' => 'Harp', 'slug' => 'harp'],
            ['name' => 'Horn', 'slug' => 'horn'],
            ['name' => 'Laud', 'slug' => 'laud'],
            ['name' => 'Lutes', 'slug' => 'lutes'],
            ['name' => 'Mandolin', 'slug' => 'mandolin'],
            ['name' => 'Mouth Harp', 'slug' => 'mouth-harp'],
            ['name' => 'Musical Bow', 'slug' => 'musical-bow'],
            ['name' => 'Octavina', 'slug' => 'octavina'],
            ['name' => 'Organ', 'slug' => 'organ'],
            ['name' => 'Percussion', 'slug' => 'percussion'],
            ['name' => 'Piano', 'slug' => 'piano'],
            ['name' => 'Plank Drum', 'slug' => 'plank-drum'],
            ['name' => 'Quill-shaped Tube', 'slug' => 'quill-shaped-tube'],
            ['name' => 'Reeds', 'slug' => 'reeds'],
            ['name' => 'Scraper', 'slug' => 'scraper'],
            ['name' => 'Slit Drum', 'slug' => 'slit-drum'],
            ['name' => 'Stamping Tube', 'slug' => 'stamping-tube'],
            ['name' => 'Synthesizer', 'slug' => 'synthesizer'],
            ['name' => 'Violin', 'slug' => 'violin'],
            ['name' => 'Xylophone', 'slug' => 'xylophone'],
            ['name' => 'Zithers', 'slug' => 'zithers'],
            ['name' => 'Absurd', 'slug' => 'absurd'],
            ['name' => 'Balagtasan', 'slug' => 'balagtasan'],
            ['name' => 'Balitaw', 'slug' => 'balitaw'],
            ['name' => 'Bodabil', 'slug' => 'bodabil'],
            ['name' => 'Brechtian Theater', 'slug' => 'brechtian-theater'],            ['name' => 'Carillo', 'slug' => 'carillo'],
            ['name' => "Children's Theater", 'slug' => 'childrens-theater'],
            ['name' => 'Dapit', 'slug' => 'dapit'],
            ['name' => 'Dotoc', 'slug' => 'dotoc'],
            ['name' => 'Theater Drama', 'slug' => 'theater-drama'],
            ['name' => 'Drama Simboliko', 'slug' => 'drama-simboliko'],
            ['name' => 'Dramatic Monologue', 'slug' => 'dramatic-monologue'],
            ['name' => 'Duplo', 'slug' => 'duplo'],
            ['name' => 'Flores', 'slug' => 'flores'],
            ['name' => 'Hudas', 'slug' => 'hudas'],
            ['name' => 'Huling Hapunan', 'slug' => 'huling-hapunan'],
            ['name' => 'Komedya', 'slug' => 'komedya'],
            ['name' => 'Loa', 'slug' => 'loa'],
            ['name' => 'Moros Y Cristianos', 'slug' => 'moros-y-cristianos'],
            ['name' => 'Moryonan/Moriones', 'slug' => 'moryonan-moriones'],
            ['name' => 'Musical Theater', 'slug' => 'musical-theater'],
            ['name' => 'Osana', 'slug' => 'osana'],
            ['name' => 'Paghuhugas ng Paa', 'slug' => 'paghuhugas-ng-paa'],
            ['name' => 'Pangangaluluwa', 'slug' => 'pangangaluluwa'],
            ['name' => 'Panunuluyan', 'slug' => 'panunuluyan'],
            ['name' => 'Pastores', 'slug' => 'pastores'],
            ['name' => 'Puppet Theater', 'slug' => 'puppet-theater'],
            ['name' => 'Realism', 'slug' => 'realism'],
            ['name' => 'Ritual', 'slug' => 'ritual'],
            ['name' => 'Salubong', 'slug' => 'salubong'],
            ['name' => 'San Roque', 'slug' => 'san-roque'],
            ['name' => 'Sarsuwela', 'slug' => 'sarsuwela'],
            ['name' => 'Saynete', 'slug' => 'saynete'],
            ['name' => 'Siete Palabras', 'slug' => 'siete-palabras'],
            ['name' => 'Sinakulo', 'slug' => 'sinakulo'],
            ['name' => 'Soledad', 'slug' => 'soledad'],
            ['name' => 'Stand-up Comedy', 'slug' => 'stand-up-comedy'],
            ['name' => 'Street Theater', 'slug' => 'street-theater'],
            ['name' => 'Tatlong Hari', 'slug' => 'tatlong-hari'],
            ['name' => 'Tubong', 'slug' => 'tubong'],
            ['name' => 'Tula-dula', 'slug' => 'tula-dula'],
            ['name' => 'Velada', 'slug' => 'velada'],
            ['name' => 'Via Crucis', 'slug' => 'via-crucis'],
            ['name' => 'Advertising Art', 'slug' => 'advertising-arts'],
            ['name' => 'Assemblage', 'slug' => 'assemblage'],
            ['name' => 'Bamboo Art', 'slug' => 'bamboo-art'],
            ['name' => 'Basketry', 'slug' => 'basketry'],
            ['name' => 'Book Design', 'slug' => 'book-design'],
            ['name' => 'Dress', 'slug' => 'dress'],
            ['name' => 'Effigies', 'slug' => 'effigies'],
            ['name' => 'Embroidery', 'slug' => 'embroidery'],
            ['name' => 'Food Art', 'slug' => 'food-art'],
            ['name' => 'Furniture', 'slug' => 'furniture'],
            ['name' => 'Installation and Site-Specific Art', 'slug' => 'installation-and-site-specific-art'],
            ['name' => 'Komiks and Editorial Cartoon', 'slug' => 'komiks-and-editorial-cartoon'],
            ['name' => 'Leaf Art', 'slug' => 'leaf-art'],
            ['name' => 'Mat Weaving', 'slug' => 'mat-weaving'],
            ['name' => 'Metalcraft', 'slug' => 'metalcraft'],
            ['name' => 'Multimedia', 'slug' => 'multimedia'],
            ['name' => 'Painting and Related Forms', 'slug' => 'painting-and-related-forms'],
            ['name' => 'Paper Art', 'slug' => 'paper-art'],
            ['name' => 'Performance Art', 'slug' => 'performance-art'],
            ['name' => 'Personal Ornaments', 'slug' => 'personal-ornaments'],
            ['name' => 'Photography', 'slug' => 'photography'],
            ['name' => 'Pottery', 'slug' => 'pottery'],
            ['name' => 'Printmaking', 'slug' => 'printmaking'],
            ['name' => 'Sculpture', 'slug' => 'sculpture'],
            ['name' => 'Tattoo Art', 'slug' => 'tattoo-art'],
            ['name' => 'Textile Weaving', 'slug' => 'textile-weaving'],
            ['name' => 'Video Art', 'slug' => 'video-art'],

        ];
        foreach($tags as $tag) {
            \App\Models\Tag::create($tag);
        }

        // \App\Models\Tag::factory()->create([

        // ]);
    }
}
