<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('entities', function (Blueprint $table) {
            $table->id();
            $table->string('archivist')->nullable();
            $table->text('work')->nullable();
            $table->text('material')->nullable();
            $table->string('code')->unique()->nullable();
            $table->text('category')->nullable();
            $table->text('title')->nullable();
            $table->text('slug')->unique()->nullable();
            $table->text('alternate-title')->nullable();
            $table->dateTime('date')->nullable();
            $table->string('place')->nullable();
            $table->text('description')->nullable();
            $table->text('reference')->nullable();
            $table->text('open_access_link')->nullable();
            $table->text('language')->nullable();
            $table->text('company')->nullable();
            $table->text('series')->nullable();
            $table->text('opening_remarks')->nullable();
            $table->text('closing_remarks')->nullable();
            $table->text('speaker')->nullable();
            $table->text('lecturer')->nullable();
            $table->text('moderator')->nullable();
            $table->text('participants')->nullable();
            $table->text('film')->nullable();
            $table->text('play')->nullable();
            $table->text('screenwriter')->nullable();
            $table->text('scriptwriter')->nullable();
            $table->text('writer')->nullable();
            $table->text('playwright')->nullable();
            $table->text('librettist')->nullable();
            $table->text('adaptor')->nullable();
            $table->text('adapted_from')->nullable();
            $table->text('based_on')->nullable();
            $table->text('translator')->nullable();
            $table->text('concept')->nullable();
            $table->text('director')->nullable();
            $table->text('associate_director')->nullable();
            $table->text('assistant_director')->nullable();
            $table->text('assistant_to_the_director')->nullable();
            $table->text('direction_consultant')->nullable();
            $table->text('program_director')->nullable();
            $table->text('project_director')->nullable();
            $table->text('artistic_director')->nullable();
            $table->text('artistic_consultant')->nullable();
            $table->text('fashion_director')->nullable();
            $table->text('ballet_master')->nullable();
            $table->text('regisseur')->nullable();
            $table->text('dramaturg')->nullable();
            $table->text('creative_director')->nullable();
            $table->text('director_of_photography')->nullable();
            $table->text('camera')->nullable();
            $table->text('musical_director')->nullable();
            $table->text('musical_arranger')->nullable();
            $table->text('stage_director')->nullable();
            $table->text('assistant_stage_director')->nullable();
            $table->text('composer')->nullable();
            $table->text('music')->nullable();
            $table->text('lyricist')->nullable();
            $table->text('performers')->nullable();
            $table->text('ventriloquist')->nullable();
            $table->text('cast')->nullable();
            $table->text('narrator')->nullable();
            $table->text('host')->nullable();
            $table->text('executive_producer')->nullable();
            $table->text('associate_producer')->nullable();
            $table->text('producer')->nullable();
            $table->text('production_designer')->nullable();
            $table->text('production_supervisor')->nullable();
            $table->text('production_manager')->nullable();
            $table->text('associate_production_manager')->nullable();
            $table->text('deputy_production_manager')->nullable();
            $table->text('assistant_production_manager')->nullable();
            $table->text('production_coordinator')->nullable();
            $table->text('editor')->nullable();
            $table->text('visual_effects')->nullable();
            $table->text('production_and_costume_consultant')->nullable();
            $table->text('set_consultant')->nullable();
            $table->text('set_designer')->nullable();
            $table->text('set_design_assistant')->nullable();
            $table->text('costume_designer')->nullable();
            $table->text('costume_consultant')->nullable();
            $table->text('make_up_artist')->nullable();
            $table->text('production_stylist')->nullable();
            $table->text('fashion_designer')->nullable();
            $table->text('lighting_designer')->nullable();
            $table->text('associate_lighting_designer')->nullable();
            $table->text('lighting_design_consultant')->nullable();
            $table->text('lighting_design_assistant')->nullable();
            $table->text('sound_designer')->nullable();
            $table->text('assistant_sound_designer')->nullable();
            $table->text('sound_engineer')->nullable();
            $table->text('choreographer')->nullable();
            $table->text('guest_faculty')->nullable();
            $table->text('technical_director')->nullable();
            $table->text('assistant_technical_director')->nullable();
            $table->text('technical_direction_assistant')->nullable();
            $table->text('stage_manager')->nullable();
            $table->text('assistant_stage_manager')->nullable();
            $table->text('deputy_stage_manager')->nullable();
            $table->text('stage_management_assistant')->nullable();
            $table->text('audio_visual_designer')->nullable();
            $table->text('video_projection_designer')->nullable();
            $table->text('video_projection_design_assistant')->nullable();
            $table->text('video_operator')->nullable();
            $table->text('music_director')->nullable();
            $table->text('assistant_music_director')->nullable();
            $table->text('arranger')->nullable();
            $table->text('conductor')->nullable();
            $table->text('choirmaster')->nullable();
            $table->text('orchestra')->nullable();
            $table->text('tenor')->nullable();
            $table->text('countertenor')->nullable();
            $table->text('soprano')->nullable();
            $table->text('bass_baritone')->nullable();
            $table->text('baritone')->nullable();
            $table->text('mezzo_soprano')->nullable();
            $table->text('alto')->nullable();
            $table->text('bandurria')->nullable();
            $table->text('bass')->nullable();
            $table->text('bass_guitar')->nullable();
            $table->text('bassoon')->nullable();
            $table->text('cello')->nullable();
            $table->text('clarinet')->nullable();
            $table->text('contrabass')->nullable();
            $table->text('drums')->nullable();
            $table->text('english_horn')->nullable();
            $table->text('flute')->nullable();
            $table->text('french_horn')->nullable();
            $table->text('guitar')->nullable();
            $table->text('harp')->nullable();
            $table->text('keyboard')->nullable();
            $table->text('oboe')->nullable();
            $table->text('marimba')->nullable();
            $table->text('percussion')->nullable();
            $table->text('piano')->nullable();
            $table->text('viola')->nullable();
            $table->text('violin')->nullable();
            $table->text('saxophone')->nullable();
            $table->text('string_quartet')->nullable();
            $table->text('timpani')->nullable();
            $table->text('trombone')->nullable();
            $table->text('trumpet')->nullable();
            $table->text('tuba')->nullable();
            $table->text('vocals')->nullable();
            $table->text('musicians')->nullable();
            $table->text('artist')->nullable();
            $table->text('curator')->nullable();
            $table->text('author')->nullable();
            $table->text('project_coordinator')->nullable();
            $table->text('publisher')->nullable();
            $table->text('contributing_writer')->nullable();
            $table->text('photographer')->nullable();
            $table->text('camera_operator')->nullable();
            $table->text('camera_setup')->nullable();
            $table->text('shooting_schedule')->nullable();
            $table->text('format')->nullable();
            $table->text('technique')->nullable();
            $table->text('measurement')->nullable();
            $table->string('edition')->nullable();
            $table->text('color')->nullable();
            $table->text('inscription')->nullable();
            $table->text('extension')->nullable();
            $table->string('resolution', 25)->nullable();
            $table->string('frame_rate', 25)->nullable();
            $table->string('aspect_ratio', 25)->nullable();
            $table->string('audio', 25)->nullable();
            $table->string('duration', 25)->nullable();
            $table->text('wholeness')->nullable();
            $table->unsignedInteger('file_count')->nullable();
            $table->string('total_size', 25)->nullable();
            $table->text('color_space')->nullable();
            $table->text('video_description')->nullable();
            $table->text('audio_description')->nullable();
            $table->text('notes')->nullable();
            $table->year('accession_year')->nullable();
            $table->text('loan_history')->nullable();
            $table->text('ccp_collection')->nullable();
            $table->string('shelf_number', 25)->nullable();
            $table->string('inventory_number', 25)->nullable();
            $table->string('tape_number', 25)->nullable();
            $table->string('hard_drive', 25)->nullable();
            $table->string('server', 25)->nullable();
            $table->text('access')->nullable();
            $table->string('citation')->nullable();
            $table->string('credit_line')->nullable();
            $table->string('precup')->nullable();
            $table->text('image')->nullable();
            $table->foreignId('collection_id')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('entities');
    }
};
