<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Entity extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'archivist',
        'thumbnail',
        'work',
        'material',
        'code',
        'category',
        'title',
        'slug',
        'alternate-title',
        'date',
        'place',
        'description',
        'reference',
        'open_access_link',
        'language',
        'company',
        'series',
        'opening_remarks',
        'closing_remarks',
        'speaker',
        'lecturer',
        'moderator',
        'participants',
        'film',
        'play',
        'screenwriter',
        'scriptwriter',
        'writer',
        'playwright',
        'librettist',
        'adaptor',
        'adapted_from',
        'based_on',
        'translator',
        'concept',
        'director',
        'associate_director',
        'assistant_director',
        'assistant_to_the_director',
        'direction_consultant',
        'program_director',
        'project_director',
        'artistic_director',
        'artistic_consultant',
        'fashion_director',
        'ballet_master',
        'regisseur',
        'dramaturg',
        'creative_director',
        'director_of_photography',
        'camera',
        'musical_director',
        'musical_arranger',
        'stage_director',
        'assistant_stage_director',
        'composer',
        'music',
        'lyricist',
        'performers',
        'ventriloquist',
        'cast',
        'narrator',
        'host',
        'executive_producer',
        'associate_producer',
        'producer',
        'production_designer',
        'production_supervisor',
        'production_manager',
        'associate_production_manager',
        'deputy_production_manager',
        'assistant_production_manager',
        'production_coordinator',
        'editor',
        'visual_effects',
        'production_and_costume_consultant',
        'set_consultant',
        'set_designer',
        'set_design_assistant',
        'costume_designer',
        'costume_consultant',
        'make_up_artist',
        'production_stylist',
        'fashion_designer',
        'lighting_designer',
        'associate_lighting_designer',
        'lighting_design_consultant',
        'lighting_design_assistant',
        'sound_designer',
        'assistant_sound_designer',
        'sound_engineer',
        'choreographer',
        'guest_faculty',
        'technical_director',
        'assistant_technical_director',
        'technical_direction_assistant',
        'stage_manager',
        'assistant_stage_manager',
        'deputy_stage_manager',
        'stage_management_assistant',
        'audio_visual_designer',
        'video_projection_designer',
        'video_projection_design_assistant',
        'video_operator',
        'music_director',
        'assistant_music_director',
        'arranger',
        'conductor',
        'choirmaster',
        'orchestra',
        'tenor',
        'countertenor',
        'soprano',
        'bass_baritone',
        'baritone',
        'mezzo_soprano',
        'alto',
        'bandurria',
        'bass',
        'bass_guitar',
        'bassoon',
        'cello',
        'clarinet',
        'contrabass',
        'drums',
        'english_horn',
        'flute',
        'french_horn',
        'guitar',
        'harp',
        'keyboard',
        'oboe',
        'marimba',
        'percussion',
        'piano',
        'viola',
        'violin',
        'saxophone',
        'string_quartet',
        'timpani',
        'trombone',
        'trumpet',
        'tuba',
        'vocals',
        'musicians',
        'artist',
        'curator',
        'author',
        'project_coordinator',
        'publisher',
        'contributing_writer',
        'photographer',
        'camera_operator',
        'camera_setup',
        'shooting_schedule',
        'format',
        'technique',
        'measurement',
        'edition',
        'color',
        'inscription',
        'extension',
        'resolution',
        'frame_rate',
        'aspect_ratio',
        'audio',
        'duration',
        'wholeness',
        'file_count',
        'total_size',
        'color_space',
        'video_description',
        'audio_description',
        'notes',
        'accession_year',
        'loan_history',
        'ccp_collection',
        'shelf_number',
        'inventory_number',
        'tape_number',
        'hard_drive',
        'server',
        'access',
        'citation',
        'credit_line',
        'precup',
        'collection_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'date' => 'datetime',
        'file_count' => 'integer',
        'collection_id' => 'integer',
        'language' => 'array',
    ];

    public function requests(): BelongsToMany
    {
        return $this->belongsToMany(Request::class);
    }

    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }

    public function collection(): BelongsTo
    {
        return $this->belongsTo(Collection::class);
    }
}
